### ISSUE TITLE
No exported Commands

### ISSUE THREAD

**Issue by clandeck** [dell/DellPEWSMANTools#10]
When I put the downloded content to the powershell modules folder and do a 
get-module -listavailable I get:

Get-Module -listavailable
    Directory: C:\Program Files\WindowsPowerShell\Modules\DellPEWSMANTools-master
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.0.0    DellPEWSManTools

There are no exported commands.

**Comment by rchaganti** [comment]
Please make sure you are copying the DellPEWSMANTools folder only from the repo. that is the actual module folder.
