### ISSUE TITLE
[enhancement] Export-PEServerConfigurationProfile update

### ISSUE THREAD

**Issue by DexterPOSH** [dell/DellPEWSMANTools#2]
Update the Export-PESServerConfigurationProfile function to export .json SCP files and the ability to dump these files locally, without the need of the SMB share.

**Comment by aderusha** [comment]
The requirement to dump to a share is pretty restrictive in environments for OOB management interfaces (like iDRAC) live on an isolated VLAN with firewall rules preventing outward communication.  RACADM.exe is our only solution at the moment but a PowerShell native approach would be great!

**Comment by rchaganti** [comment]
@aderusha Which generation of servers are you using? For 14th Gen servers, we can stream the SCP to a local file. I will update the function to add that functionality.

**Comment by aderusha** [comment]
My current customer just purchased 500 14gen PEs and will likely be purchasing several thousand more.  This functionality would be great, and 14gen only is not a problem at all!

**Comment by rchaganti** [comment]
Great! Give me a couple of days and I will show a working function early next week.

**Comment by aderusha** [comment]
If I'm adding things to the wishlist here (and I am very thankful for it), I'd ask that the output be available in XML format so it's compatible w/ existing iDRAC profile imports/exports from the web interface.

**Comment by rchaganti** [comment]
You should be able to choose that as a part of the command.

**Comment by aderusha** [comment]
Any update on this?

**Comment by rchaganti** [comment]
I finally had the time to close this. #8 resolves this request. Docs are not up to date but here is how you use this.

# Export as XML
Export-PEServerConfigurationProfile -iDRACSession $session -ShareType LOCAL -LocalFilePath C:\Dell\Test.xml -Verbose -Wait -ExportFormat XML

or 

# By default, the SCP gets exported as JSON
Export-PEServerConfigurationProfile -iDRACSession $session -ShareType LOCAL -LocalFilePath C:\Dell\Test.json -Verbose -Wait 

-Wait is important.
